version: "3.9"

services:
  nabi-postgres:
    image: postgres:16.2
    container_name: "nabidb-postgresql"
    restart: always
    ports:
      - "5432"
    env_file:
      - postgres.env

  nabi-cachegrand:
    image: cachegrand/cachegrand-server:latest
    container_name: "nabi-cachegrand"
    restart: always
    ports:
      - "6379"