[versions]
caching = "0.4.0"
coroutines = "1.8.1"
exposed = "0.51.1"
hikari = "5.1.0"
interaktions = "0.0.22-SNAPSHOT"
icu4j = "75.1"
jda = "5.0.0-beta.23"
kotlin = "2.0.0"
ktor = "2.3.11"
logback = "1.4.12"
kord = "0.15.0-SNAPSHOT"
kotlin-serialization = "1.6.3"
ktoml = "0.5.1"
postgresql = "42.7.3"
prometheus = "0.16.0"
redisson = "3.31.0"
zstd = "1.5.6-3"

[libraries]
# Discord libraries/frameworks
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }

kord-common = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-gateway = { module = "dev.kord:kord-gateway", version.ref = "kord" }
kord-rest = { module = "dev.kord:kord-rest", version.ref = "kord" }
interaktions-gateway = { module = "com.github.catgirlclient.DiscordInteraKTions:gateway-kord", version.ref = "interaktions" }
interaktions-webserver = { module = "com.github.catgirlclient.DiscordInteraKTions:webserver-ktor-kord", version.ref = "interaktions" }

# Database
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }

# Caching
cache-api = { module = "dev.kord.cache:cache-api", version.ref = "caching" }
cache-map = { module = "dev.kord.cache:cache-map", version.ref = "caching" }
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }

# Config/Locale Purposes
kotlin-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlin-serialization" }
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
ktoml-file = { module = "com.akuleshov7:ktoml-file", version.ref = "ktoml" }
icu4j = { module = "com.ibm.icu:icu4j", version.ref = "icu4j" }

zstd = { module = "com.github.luben:zstd-jni", version.ref = "zstd" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor"}
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-utils = { module = "io.ktor:ktor-utils", version.ref = "ktor" }

# Logger
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
prometheus-httpserver = { module = "io.prometheus:simpleclient_httpserver", version.ref = "prometheus" }

[bundles]
discord = [
    "jda",
    "kord-common",
    "kord-core",
    "kord-gateway",
    "kord-rest",
    "interaktions-gateway",
    "interaktions-webserver"
]
database = [
    "postgresql",
    "hikaricp",
    "exposed-core",
    "exposed-dao",
    "exposed-jdbc",
    "exposed-kotlin-datetime"
]
parsers = [
    "kotlin-hocon",
    "ktoml-core",
    "ktoml-file",
    "icu4j"
]

ktor = [
    "zstd",
    "ktor-http",
    "ktor-client-encoding",
    "ktor-client-core",
    "ktor-utils"
]

caching = [
    "cache-api",
    "cache-map",
    "redisson"
]

logger = [
    "logback",
    "prometheus-httpserver"
]