version: "3.9"

services:
  nabi-postgresql:
    image: postgres:17.2
    container_name: "nabidb-postgresql"
    restart: always
    ports:
      - "5432"
    env_file:
      - ../postgres.env

  nabi-dragonflydb:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    pull_policy: 'always'
    container_name: "nabi-dragonfly"
    restart: always
    ports:
      - "6380:6379"